index.js

This PR adds some additional warnings when the google maps API configuration seems incorrect. 
The Google API Client ID can be used instead of the API Key, and they can not be used at the same time.
The channel parameter can only be used when using a Client ID.
https://developers.google.com/maps/documentation/javascript/get-api-key#premium-auth

Add additional warnings for Google Maps API usage

---

addon/components/g-map.js
addon/components/g-map/directions.js
addon/components/g-map/info-window.js
addon/components/g-map/map-component.js
addon/utils/public-api.js
tests/integration/components/g-map-test.js
tests/integration/components/g-map/autocomplete-test.js
tests/integration/components/g-map/circle-test.js
tests/integration/components/g-map/control-test.js
tests/integration/components/g-map/directions-test.js
tests/integration/components/g-map/info-window-test.js
tests/integration/components/g-map/marker-test.js
tests/integration/components/g-map/overlay-test.js
tests/integration/components/g-map/polyline-test.js
tests/integration/components/g-map/route-test.js
tests/integration/components/g-map/waypoint-test.js

* Cleanly expose parts of map components using proxies and getters.
* Make generating the public API much cleaner internally.
* Consistently return the public API in actions.

Improve the public API object

---

addon/components/g-map.js
addon/components/g-map/autocomplete.js
addon/components/g-map/circle.js
addon/components/g-map/info-window.js
addon/components/g-map/map-component.js
addon/components/g-map/marker.js
addon/components/g-map/overlay.js
addon/components/g-map/route.js
addon/components/g-map/waypoint.js
addon/mixins/process-options.js
addon/mixins/register-events.js
tests/integration/components/g-map-test.js

* Correctly expose '_trigger' method and allow passing arbitrary
arguments.
* Expose `place` in autocomplete.
* Remove usage of `const`.
* Add assertions to base map-component.
* Remove unused `getPosition` method from marker component.
* Cleanup options processing.
* Collect extracted event names in `_eventAttrs`. Use this array to
filter out attrs when processing options.
* Ensure `events` is an object, not an array of event names.
* Allow registering events using both an `events` hash and by passing
attributes.

Refactor internals – 🎬 2 

---

package.json
yarn.lock

From what I can tell, this proxy plugin looks like it might not be used? I've checked for Proxy usage and don't see any raw browser usage ... If so, thought it was worth removing.
It's throwing warnings in the terminal about the need to upgrade to a newer babel env approach and mentions specifically in the readme to not use in production environments because of negative performance impacts: https://github.com/krzkaczor/babel-plugin-proxy

Remove a seemingly unused proxy plugin that throws warnings

---

index.js

This PR fixes the breaking change in treeshaking/whitelisting introduced in ember-google-maps 2.0.0.
Closes #24 (thanks to @acorncom for finding the issue)

2.x treeshaking/whitelisting fix

---

package.json

Seems that 855df068af6b40fc8af2e68ce20368487dbc3733 broke the package, using the latest versions ends up with:
```
Uncaught Error: Could not find module `ember-concurrency` imported from `ember-google-maps/components/g-map`
```
I've moved the `ember-concurrency` package from `devDependencies` to `dependencies` since it currently is a runtime requirement of `ember-google-maps`. This fixes the issue.

Move ember-concurrency to dependencies.

---

package.json
yarn.lock

This wasn't caught in tests on Travis as the yarn lock file is ignored. And I'm assuming it wasn't caught on your machine because you'd done an `npm link` / `yarn link`? 😄

Bumped ember-google-maps-sample-addon to fix tests locally

---

addon/components/g-map/map-component.js
addon/utils/public-api.js

Fixes #39 . By making this change, we give addon authors a chance to interact with the map and do any needed tear down prior to tearing down the component registration with our publicAPI proxy while still using exclusively our `publicAPI`. A `map` property *does* currently exist on the `MapComponent` and children, but our naming implies that it might not in the future.
@sandydoo I'm happy to add some tests here if we want (doing that using an in-repo addon starts looking quite appealing 😉 ), but wanted to push this up to get your input on it before working up the tests.

Add finer grained control over de-registration of a component from the publicAPI proxy

---

addon/components/g-map/overlay.js

On a client project I'm working on, I was using the overlay component in some acceptance tests as I built things out (and we were using api keys in the test environment). We won't be doing that long-term, but in certain scenarios I was triggering `set on destroyed object` errors as seen below:
I couldn't replicate the issue easily in the test suite for this addon (though I got it to do it occasionally), so it's possible it occurs more when using "classic" test helpers as my client is. But I thought I should send this in to see if you want to merge it.
Seems unlikely that in daily use this issue would be hit that often. But it's technically a bug ... 😄  
If you've got ideas on better ways to replicate the issue, I'm happy to add some tests here ...

Add a few defensive guards against set on destroyed object errors

---

addon/components/g-map/control.js
tests/integration/components/g-map/control-test.js

In certain cases where your designer has ambitious designs, it's quite helpful to be able to specify a class name on a control:
```hbs
{{#g-map lat="" lng="" as |g|}}
{{g.control position="TOP_CENTER" className="sidebar"}}
{{/g-map}}
```
I opted for `className` instead of `class` to avoid confusion when used in conjunction with angle bracket syntax down the road. At the moment, I don't believe the syntax below works (I don't believe yielded values can be called with dot syntax) but if they can in the future, we want to avoid the headaches below:
```hbs
<G.Control class="sidebar">
<G.Control @class="sidebar">
<G.Control @className="sidebar">
```

Add ability to specify a class name for the control component

---

addon/services/google-maps-api.js
tests/unit/services/google-maps-api-test.js

Adds a public `buildGoogleMapsUrl` function to the addon's service to allow runtime URL modification.
Closes #3.

Add optional runtime configuration to API loader

---

addon/components/g-map.js
addon/components/g-map/autocomplete.js
addon/components/g-map/circle.js
addon/components/g-map/control.js
addon/components/g-map/directions.js
addon/components/g-map/info-window.js
addon/components/g-map/map-component.js
addon/components/g-map/marker.js
addon/components/g-map/overlay.js
addon/components/g-map/polyline.js
addon/components/g-map/route.js
addon/components/g-map/waypoint.js
addon/mixins/process-options.js
addon/mixins/register-events.js
addon/templates/components/g-map/directions.hbs
addon/utils/options-and-events.js
tests/integration/components/g-map/overlay-test.js

Drop mixins

---

addon/components/g-map.js
addon/components/g-map/canvas.js
addon/templates/components/g-map/canvas.hbs
package.json
tests/integration/components/g-map/canvas-test.js
yarn.lock

I noticed that [this commit](https://github.com/sandydoo/ember-google-maps/commit/86c6dcfb726636187ad033781a4d268b2d089989) doesn't work when using AngleBrackets. `this.class` will be undefined if you pass classes like this
```handlebars
...
<g.canvas class="test" />
...
```
This makes sure that classes are properly applied to the div when using AngleBrackets invocation. Using splattributes shouldn't be a problem since the Readme mentions Ember 3.4+, right?

fix: Splat html attributes on the canvas div element

---

index.js

This PR adds support for cloud based map stylings (https://developers.google.com/maps/documentation/javascript/cloud-based-map-styling)
Adding the `mapId` to the url at runtime seems wrong in this particular case and can result in flickering of different styles.

Add support for Cloud-based Map Styling

---

package.json
yarn.lock

The `Plugin` from `broccoli-plugin` is now a class in newer versions, so
all sorts of errors can happen in new apps. We don’t really care which
version is used — our use-case is super basic.

Loosen `broccoli-funnel` dependency

---

addon/effects/tracking.js
package.json
yarn.lock

In particular, this fixes builds for apps that are running on older versions of
`babel-plugin-ember-modules-api-polyfill`.

Fix runloop imports for older Ember version

---

addon/components/g-map.js
docs/app/templates/docs/components.hbs
docs/code-snippets/handle-on-load.js
docs/code-snippets/map-on-load.hbs
docs/code-snippets/map-public-api.js
tests/integration/components/g-map-test.js

Currently, it doesn’t even work properly because we don’t do the
expensive tracking anymore. I reckon it’s not even a necessary feature:
you should use more specific `on*` events on the components you care
about.

Remove `onComponentsLoad` hook

---

addon/component-managers/map-component-manager.js
addon/components/g-map.js

Let's set up the test waiters in the map component manager. This is a
good spot to add waiting for all the map components. On the map itself,
we additionally wait for the idle event.

Improve how we wait for the map in tests

---

addon/utils/options-and-events.js
docs/app/templates/docs/complex-ui.hbs
docs/app/templates/docs/components.hbs
docs/app/templates/docs/events.hbs
docs/app/templates/docs/map.hbs
docs/app/templates/examples/sweet-rentals.hbs
docs/code-snippets/handle-once-on-idle.js
docs/code-snippets/map-once-on-idle.hbs
docs/code-snippets/sweet-rentals-map.hbs
tests/integration/components/g-map-test.js

You can now register events that will trigger just once. This uses Google Maps’ `addListenerOnce`.
This can be used to replace the old `onLoad` event, which was a custom event provided by `ember-google-maps`.
Before:
```hbs
<GMap @lat="this.lat" @lng="this.lng" @onLoad={{this.onMapLoad}} />
```
After:
```hbs
<GMap @lat="this.lat" @lng="this.lng" @onceOnIdle={{this.onMapLoad}} />
```

Add `onceOn` events that fire only once

---

addon/components/g-map.js
build-tests/fixtures/treeshaking-test/tests/integration/shakedown-test.js
tests/integration/components/g-map-test.js

The custom `onLoad` event has been deprecated. You should replace it with `onceOnIdle`.
If you had the following:
```js
<GMap @lat={{this.lat}} @lng={{this.lng}} @onLoad={{this.didLoadMap}} />
```
Replace it with:
```js
<GMap @lat={{this.lat}} @lng={{this.lng}} @onceOnIdle={{this.didLoadMap}} />
```

Deprecate the `onLoad` event

---

addon/components/g-map/autocomplete.hbs
addon/components/g-map/canvas.hbs
addon/components/g-map/control.hbs
addon/components/g-map/overlay.hbs
addon/modifiers/g-map/did-insert.js
app/modifiers/g-map/did-insert.js
package.json
tests/integration/components/g-map/autocomplete-test.js
tests/integration/modifiers/g-map/did-insert-test.js
yarn.lock

- Replace `@ember/render-modifiers` with a simple `did-insert` modifier.
- Use the updated `ember-modifier` package with support for the new modifier capabilities.
Fixes #102.

Fix modifier manager capabilities deprecation

---

addon/components/g-map/directions.js
docs/app/controllers/docs.js
docs/package.json
docs/yarn.lock
package.json
yarn.lock

This fork fixes the Ember global deprecation in newer Ember versions.
The maintainers don't want to patch this and are preparing to drop
support for anything older than `3.24`. What are you gonna do.
Also, drop `tracked-toolbox` becasue we weren't using it.

Temporarily switch to a patched version of `tracked-maps-and-sets`

---

addon/utils/options-and-events.js
tests/integration/components/g-map-test.js

We were setting `center` to `undefined` when drawing a map without
coordinates. That actually produced a reasonable error message because
the setter returned `false` when trying to delete the non-existent
`center` key from the set cache.
We now return `true` from the setter so that it doesn't error out.
This also means that `center` is now an optional argument.
Fixes #120.

Don't error out when setting an undefined option

---

docs/app/router.js
docs/app/routes/docs.js
docs/app/routes/not-found.js
docs/app/templates/not-found.hbs

This was accidentally sending everyone to `getting-started` when
reloading or navigating to a docs subroute directly.
[skip ci]

Fix redirect on 404 in docs

---

addon/components/g-map.js
addon/components/g-map/map-component.js
tests/integration/components/g-map/marker-test.js

I forgot to reimplement this before releasing the Octane rewrite 🤦 Since we weren't unregistering components, if you drew a marker and then removed it, the map would still say you had one marker on the map.

Unregister components on teardown

---

addon/components/g-map/directions.js
addon/effects/tracking.js
tests/integration/components/g-map/directions-test.js

`ember-concurrency` tracks its internal properties, so it ends up
triggering the effect a second time once it resolves. I guess we
could "changeset" the options to avoid this, but there's more. Because
it runs in the same computation as this effect, you can't even
check`isRunning` without triggering an error from Glimmer. That's not
particularly great, and I guess the solution might have to happen
upstream (scheduling or track/untrack frames). Let's see what comes out
of Glimmer's effect system and revisit.

Fix issue where directions were re-fetched when resolved

---

addon/component-managers/map-component-manager.js

Sometimes it doesn't make sense for a map component to have a dedicated
update method. But that doesn't mean that there's nothing to clean up
before running the setup method again.

Tear down components that don't have an update method

---

addon/components/g-map/control.js
tests/integration/components/g-map/control-test.js

- Remove the control from the map before rendering the new one.
- Update the tests to test changing the position of the control.
- Increase the timeout for `waitFor`. Sometimes it can take a while to
render the map.

Tear down controls properly

---

lib/ast-transforms/addon-factory.js

The `template` component isn't a valid component, so it should always be removed,
even when there aren't any addons to add to the template.

Fix errors trying to find a `template` component

---

addon/component-managers/map-component-manager.js

Don't tear down if there is no map component. That way it also
shouldn't run in FastBoot, since the setup method is never run
in FastBoot.

Fix teardown errors in FastBoot

---

lib/ast-transforms/addon-factory.js
lib/ast-transforms/canvas-enforcer.js
lib/ast-transforms/treeshaker.js

There isn't any documentation on how to write these AST plugins. Until
now, I would base the design on whatever rjwblue was doing, because,
you know, core-team and everything. With Ember@4.0 the class-based
design he uses doesn't work. The plugin now HAS to be a function that
returns an object with the visitor (see here: https://github.com/glimmerjs/glimmer-vm/blob/ef92c497c3d921af22b38a54eac1445c204c3370/packages/%40glimmer/syntax/lib/parser/tokenizer-event-handlers.ts#L318-L325)

Refactor AST plugins to match new plugin format

---

addon/services/google-maps-api.js

On the GoogleMapsApiService, the _getApi() should return window.google, not window.google.maps right?
After I install the ember-place-autocomplete addon this one is failing to load the Google Maps API. The _loadAndInitApi() function resolves window.google after it loads, and the getter directionsService() tries to access the .maps property. So returning window.google.maps on _getAPI() fails on the getter as it tries to access the maps property by a second time. I think this is a bug added like 4 months ago.
I don't know why the tests are failing, looks like the tests don't have an API Key set.

Return the `google` global from the API service if Google Maps has already been loaded

---

.github/workflows/ci.yml

`actions/setup-node@2` now supports caching yarn's cache. This seems
like a better idea than caching the node_modules folder. Sometimes
node_modules just gets corrupted for no reason.

Cache yarn's global cache of packages in CI

---

addon-test-support/index.js
addon-test-support/setup-map.js
tests/acceptance/app-test.js
tests/dummy/app/controllers/application.js
tests/dummy/app/templates/application.hbs

We’re not really testing anything useful here — our usual integration
tests cover this. But it’s nice to actually run an acceptance test in
case something breaks within that context.

Add an acceptance test to the test suite

---

addon/components/g-map.js
addon/utils/options-and-events.js
tests/integration/components/g-map-test.js

The `onLoad` event has been deprecated. You should replace it with `onceOnIdle`.
If you had the following:
```hbs
<GMap @lat={{this.lat}} @lng={{this.lng}} @onLoad={{this.didLoadMap}} />
```
Replace it with:
```hbs
<GMap @lat={{this.lat}} @lng={{this.lng}} @onceOnIdle={{this.didLoadMap}} />
```

Drop support for the `onLoad` event

---

addon/components/g-map.hbs
addon/components/g-map/control.hbs
addon/utils/options-and-events.js
lib/ast-transforms/canvas-enforcer.js
tests/integration/components/g-map/canvas-test.js

Before:
```hbs
<GMap @classNames="my-custom-class" />
```
After:
```hbs
<GMap class="my-custom-class" />
```

Drop support for `@classNames`. Use `class` instead.

---

LICENSE
LICENSE.md

The license remains MIT.
[skip ci]

Update license year, copyright holder, and formatting

---

addon/utils/options-and-events.js
tests/integration/components/g-map/overlay-test.js

`addDomListener` is now deprecated and should be replaced with the native `addEventListener` function.
https://developers.google.com/maps/documentation/javascript/releases#3.48.9

Fix deprecation warning for `addDomListener`

---

.stylelintignore
addon-test-support/setup-map.js
addon/component-managers/map-component-manager.js
addon/components/g-map.js
addon/utils/helpers.js
app/utils/helpers.js
index.js
package.json
tests/integration/addon-system-test.js
yarn.lock

* Apply the preprocessor hack for older versions of Embroider.
* Update tests to work under optimized Embroider builds.
* Remove the in-repo test addon from package.json.
* Downgrade ember-modifier to work around a bug complaining about incorrect capabilities.
Resolves #171.

Fix support for newer versions of Embroider

---

package.json
yarn.lock

Motivation: the addon using v3 is preventing the apps from upgrading to v4 (it's failing the dependency linting)

Update ember-modifier to v4

---

addon/components/g-map/control.js
addon/components/g-map/overlay.js

Glimmer doesn't seem to like DocumentFragment anymore. Replaced with a div element.

fix: resolve DocumentFragment errors in newer Ember versions

---

README.md
package.json

The new minimum bound is v3.28. Older versions may work, but we don't test against them.

Deprecate Ember v3.24 support

---

README.md

Node versions v12.x, v14.x, and v16.x are all EOL. The addon likely works with all of these, but it will no longer be tested against them and compatibility moving forward is not guaranteed.

Update the official minimum Node version to >=v18

---

addon/helpers/g-map/hash.js
app/helpers/g-map/hash.js
docs/app/templates/docs/controls.hbs
docs/app/templates/docs/directions.hbs
docs/app/templates/docs/map.hbs
docs/app/templates/examples/sweet-rentals.hbs
docs/code-snippets/basic-routes.hbs
docs/code-snippets/complex-routes.hbs
docs/code-snippets/recenter-map-control.hbs
docs/code-snippets/show-hide-controls.hbs
docs/code-snippets/sweet-rentals-map.hbs
tests/integration/components/g-map-test.js

This is a workaround to safely pass objects containing options to Google Maps. The object created by `hash` lacks a prototype chain and the map will sometimes try (and fail) to access common methods, like `hasAttribute`.
If you're passing options to any map component using `{{ hash ... }}`, replace it with `{{ g-map/hash ... }}`.
Resolves #174.

Add g-map/hash helper

---

addon/components/g-map.hbs
addon/components/g-map.js
addon/components/g-map/advanced-marker.hbs
addon/components/g-map/advanced-marker.js
addon/components/g-map/map-component.js
addon/utils/options-and-events.js
app/components/g-map/advanced-marker.js
docs/app/components/code-snippet.js
docs/app/controllers/docs.js
docs/app/controllers/docs/transit-layers.js
docs/app/router.js
docs/app/routes/docs/advanced-markers.js
docs/app/templates/docs/advanced-markers.hbs
docs/app/templates/docs/markers.hbs
docs/code-snippets/advanced-markers.hbs
docs/config/environment.js
docs/ember-cli-build.js
docs/pnpm-lock.yaml
jsconfig.json
package.json
pnpm-lock.yaml
tests/dummy/config/environment.js
tests/integration/components/g-map/advanced-marker-test.js
tests/integration/components/g-map/info-window-test.js

Since the standard marker is [deprecated](https://developers.google.com/maps/documentation/javascript/advanced-markers/migration).

feat: add advanced markers

---

addon/components/g-map.js
docs/app/controllers/docs.js
docs/app/templates/docs/advanced-markers.hbs
docs/app/templates/docs/markers.hbs
docs/code-snippets/advanced-markers.hbs
docs/code-snippets/basic-markers.hbs
docs/pnpm-lock.yaml
package.json
pnpm-lock.yaml
tests/integration/components/g-map/advanced-marker-test.js

An auto-generated `mapId` was added together with the [advanced marker
feature](#192). This should not have been done as the `mapId` is specifically
used for cloud styling and breaks "legacy" styling.

Remove default mapId from the map
